
services:
  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:5000"  # HTTP
      - "5001:5001"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
    volumes:
      - ./certs:/https   
    depends_on:
      - authservice
      - productservice


  authservice:
    build: ./AuthService
    ports:
      - 7001:7001
    depends_on:
      - redis
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7001;http://+:7000
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AuthDb;Username=postgres;Password=1231
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
    volumes:
      - ./certs:/https

  productservice:
    build: ./ProductService
    ports:
      - "6001:6001"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001;http://+:6000
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/productdb
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
    volumes:
      - ./certs:/https

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: AuthDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1231
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - apigateway
